Call pip install --upgrade nodejs
Call pip install --upgrade ipympl
Call pip install --upgrade ipython
Call pip install --upgrade ipywidgets
Call pip install --upgrade matplotlib
Call pip install --upgrade pandas
Call pip install --upgrade numpy
Call pip install --upgrade pyats
Call pip install --upgrade scipy
Call pip install --upgrade pyserial